channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.8.0
  - category-encoders==2.6.3
  - cloudpickle==2.2.1
  - numpy==1.26.2
  - packaging==23.2
  - pandas==2.1.3
  - psutil==5.9.6
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.3
name: mlflow-env
